import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warbot Scouting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white antialiased">
        {/* --- NAVIGATION BAR --- */}
        <nav className="sticky top-0 z-50 bg-black/80 backdrop-blur-md border-b border-gray-800">
  <div className="max-w-6xl mx-auto px-4 h-auto min-h-[4rem] flex flex-col md:flex-row items-center justify-between py-3 gap-4">
    <Link href="/" className="text-xl font-black tracking-tighter text-red-500 whitespace-nowrap">
      Warbot Scouting
    </Link>
    
    {/* Use overflow-x-auto so users can swipe through links on small phones */}
    <div className="flex gap-4 text-[10px] md:text-sm font-bold uppercase tracking-wide text-gray-400 overflow-x-auto pb-2 md:pb-0 w-full md:w-auto no-scrollbar">
      <Link href="/scout" className="hover:text-white whitespace-nowrap">Scout</Link>
      <Link href="/pitscout" className="hover:text-white whitespace-nowrap">Pit</Link>
      <Link href="/analysis/matches" className="hover:text-white whitespace-nowrap">Matches</Link>
      <Link href="/analysis/teams" className="hover:text-white whitespace-nowrap">Teams</Link>
      <Link href="/analysis/pick-lists" className="hover:text-white whitespace-nowrap">Picks</Link>
    </div>
  </div>
</nav>

        {/* --- PAGE CONTENT --- */}
        <main>{children}</main>
      </body>
    </html>
  );
}
